apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-role-replace-patch
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.AC Identity Management and Access Control
    policy.open-cluster-management.io/controls: PR.AC-4 Access Control
spec:
  remediationAction: enforce            # enforce to patch
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-role-replace-patch-deployments-role
        spec:
          remediationAction: inform      
          severity: high
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: deployments-role
                  namespace: default 
                rules:                 # specify rules to replace
                  - verbs:
                      - get
                    apiGroups:
                      - ''
                    resources:
                      - namespaces
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-role-replace-patch
placementRef:
  name: placement-policy-role-replace-patch
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-role-replace-patch
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-role-replace-patch
spec:
  clusterSelector:
    matchExpressions: []
