apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-role-delete
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.AC Identity Management and Access Control
    policy.open-cluster-management.io/controls: PR.AC-4 Access Control
spec:
  remediationAction: enforce # enforce to delete
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-role-delete-deployments-role
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: mustnothave # mustnothave to delete
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: deployments-role
                  namespace: default # specify namespace of the object in metadata to delete the resouce in desired namespace
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-role-delete
placementRef:
  name: placement-policy-role-delete
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: policy-role-delete
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-role-delete
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions: []
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
