apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-policy-template-sync
spec:
  template:
    spec:
      containers:
        - name: governance-policy-template-sync
          args:
            - "--zap-devel"
