apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-policy-propagator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: governance-policy-propagator
  template:
    metadata:
      labels:
        name: governance-policy-propagator
    spec:
      serviceAccountName: governance-policy-propagator
      imagePullSecrets:
        - name: multiclusterhub-operator-pull-secret
      containers:
        - name: governance-policy-propagator
          image: quay.io/stolostron/governance-policy-propagator:latest-2.2
          command:
          - governance-policy-propagator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "governance-policy-propagator"
