apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-role-audit-single-ns
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.AC Identity Management and Access Control
    policy.open-cluster-management.io/controls: PR.AC-4 Access Control
spec:
  remediationAction: inform             # inform to audit
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-role-audit-single-ns
        spec:
          remediationAction: inform      
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: Role
                metadata:
                  name: deployments-role
                rules:
                  - verbs:
                      - get
                    apiGroups:
                      - ''
                    resources:
                      - namespaces
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-role-audit-single-ns
placementRef:
  name: placement-policy-role-audit-single-ns
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-role-audit-single-ns
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-role-audit-single-ns
spec:
  clusterSelector:
    matchExpressions: []
