apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployments-role
  namespace: default
rules:
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - delete
      - patch