name: Framework KinD Hosted mode Workflow

on:
  workflow_call:
    inputs: # To specify where they're located for components, it's leveraged by our controller repos.
      hub_only_component:
        required: false
        type: string
        default: 'false'

env:
  RELEASE_BRANCH: ${{ github.event.pull_request.base.ref || github.ref_name }}

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Hosted mode Tests # Part of the check name, be careful when changing.

    runs-on: ubuntu-latest
    env:
      REGISTRY: localhost:5000

    steps:

    - name: Checkout Component Repository
      # Checkout a specific component when called from another repository
      if: ${{ github.event.repository.name != 'governance-policy-framework' }}
      uses: actions/checkout@v3
      with:
        # `repository` is inferred as the "caller" repository 
        path: component
        # `ref` is inferred as the new commit in the "caller" repository

    - name: Checkout Policy Framework
      # Checkout a stable branch when called from another repository
      if: ${{ github.event.repository.name != 'governance-policy-framework' }}
      uses: actions/checkout@v3
      with:
        repository: stolostron/governance-policy-framework
        path: framework
        ref: ${{ env.RELEASE_BRANCH }} # like main or release-*

    - name: Checkout Policy Framework
      # Checkout like "usual" when called from this repository
      if: ${{ github.event.repository.name == 'governance-policy-framework' }}
      uses: actions/checkout@v3
      with:
        # `repository` is inferred as the "caller" repository 
        path: framework
        # `ref` is inferred as the new commit

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: framework/go.mod

    - name: Bootstrap the KinD clusters for hosted mode
      working-directory: framework
      run: |
        echo "::group::make e2e-dependencies"
        make e2e-dependencies
        echo "::endgroup::"

        echo "::group::make setup hosted mode"
        make kind-bootstrap-hosted
        echo "::endgroup::"
        echo "::group::Saving kubeconfig paths for use in other steps"
    
        echo "MANAGED_KUBECONFIG=$(pwd)/kubeconfig_managed" >> $GITHUB_ENV
        echo "HUB_KUBECONFIG=$(pwd)/kubeconfig_hub" >> $GITHUB_ENV
        echo "HUB_INTERNAL_KUBECONFIG=$(pwd)/kubeconfig_hub_internal" >> $GITHUB_ENV
        echo "::endgroup::"
    
        echo "::group::test for patch step"
        export MANAGED_CONFIG=$(pwd)/kubeconfig_managed
        export HUB_CONFIG=$(pwd)/kubeconfig_hub
        export HUB_CONFIG_INTERNAL=$(pwd)/kubeconfig_hub_internal
        echo "::endgroup::"

    - name: Patch Component Image
      if: ${{ github.event.repository.name != 'governance-policy-framework' }}
      working-directory: component
      env:
        WATCH_NAMESPACE: cluster2-hosted
      run: |
        if [ "$RELEASE_BRANCH" != main ]; then
          export VERSION_TAG=latest-$(echo $RELEASE_BRANCH | cut -d'-' -f 2):
        else
          export VERSION_TAG=latest
        fi

        echo "Use $VERSION_TAG"

        echo " KIND_NAME=policy-addon-ctrl1 and the hub config as the default kubeconfig"

        echo "Using KIND_NAME=policy-addon-ctrl1 and the hub config as the default kubeconfig"
        export KIND_NAME=policy-addon-ctrl1
        export KUBECONFIG=${HUB_KUBECONFIG}

        echo "::group::make build-images"
        TAG=$(VERSION_TAG) make build-images
        echo "::endgroup::"

        echo "::group::make kind-deploy-controller-dev"
        TAG=$(VERSION_TAG) KIND_NAMESPACE=cluster2-hosted make kind-deploy-controller-dev
        echo "::endgroup::"

    - name: Run e2e tests
      working-directory: framework
      env:
        TEST_ARGS: --json-report=report.json --junit-report=report.xml --output-dir=test-output
      run: |
        make e2e-test-hosted

    - name: Debug
      if: ${{ failure() }}
      working-directory: framework
      run: |
        make e2e-debug-kind
        tar -czvf e2e-debug.tar.gz test-output/debug
    
    - name: Upload Debug Artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: fw-kind-debug-hosted-mode
        path: framework/e2e-debug.tar.gz

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: fw-kind-report-hosted-mode
        path: |
          framework/test-output/report.xml
          framework/test-output/report.json
